
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =             112
     no. of nonzeroes in lower triangle of a =             786
     no. of nonzeroes in the factor l        =            3268
     ratio of nonzeroes in factor (min/max)  =          0.1817
     number of super nodes                   =               8
     maximum order of a front matrix         =              37
     maximum size of a front matrix          =             703
     maximum size of a front trapezoid       =             658
     METIS reordering method used 
     no. of floating point ops for factor    =      4.1599D+04
     no. of floating point ops for solve     =      7.5560D+03
     ratio of flops for factor (min/max)     =          0.2365
     ratio of allocated memory (max/min)     =          1.0484
     number of positive pivots               =             112
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001066
     time (cpu & wall) for ordering          =        0.000000        0.006431
     time (cpu & wall) for other matrix prep =        0.000000        0.007928
     time (cpu & wall) for value input       =        0.000000        0.000430
     time (cpu & wall) for matrix distrib.   =        0.000000        0.017812
     time (cpu & wall) for numeric solve     =        0.015625        0.006461
     computational rate (gflops) for solve   =        0.000484        0.001169
     effective I/O rate (GB/sec) for solve   =        0.001802        0.004357

     no input or output performed

  Solver Memory allocated on core    0       =        0.278 MB
  Solver Memory allocated on core    1       =        0.270 MB
  Solver Memory allocated on core    2       =        0.274 MB
  Solver Memory allocated on core    3       =        0.265 MB
  Total Solver Memory allocated by all cores =        1.087 MB

