
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =               6
     no. of nonzeroes in lower triangle of a =              17
     no. of nonzeroes in the factor l        =             129
     ratio of nonzeroes in factor (min/max)  =          0.2727
     number of super nodes                   =               1
     maximum order of a front matrix         =               6
     maximum size of a front matrix          =              21
     maximum size of a front trapezoid       =              21
     METIS reordering method used 
     no. of floating point ops for factor    =      9.1000D+01
     no. of floating point ops for solve     =      6.0000D+01
     ratio of flops for factor (min/max)     =          0.5122
     ratio of allocated memory (max/min)     =          1.0009
     number of positive pivots               =               6
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               3
     number of threads per process used      =               1
     number of cores used                    =               3
     time (cpu & wall) for structure input   =        0.000000        0.001060
     time (cpu & wall) for ordering          =        0.000000        0.008612
     time (cpu & wall) for other matrix prep =        0.015625        0.010569
     time (cpu & wall) for value input       =        0.000000        0.000567
     time (cpu & wall) for matrix distrib.   =        0.031250        0.037616
     time (cpu & wall) for numeric solve     =        0.015625        0.008929
     computational rate (gflops) for solve   =        0.000004        0.000007
     effective I/O rate (GB/sec) for solve   =        0.000014        0.000025

     no input or output performed

  Solver Memory allocated on core    0       =        0.201 MB
  Solver Memory allocated on core    1       =        0.201 MB
  Solver Memory allocated on core    2       =        0.201 MB
  Total Solver Memory allocated by all cores =        0.602 MB

