
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =             416
     no. of nonzeroes in lower triangle of a =            3174
     no. of nonzeroes in the factor l        =           15781
     ratio of nonzeroes in factor (min/max)  =          0.3904
     number of super nodes                   =              27
     maximum order of a front matrix         =              63
     maximum size of a front matrix          =            2016
     maximum size of a front trapezoid       =            1863
     METIS reordering method used 
     no. of floating point ops for factor    =      3.9058D+05
     no. of floating point ops for solve     =      4.5744D+04
     ratio of flops for factor (min/max)     =          0.2876
     ratio of allocated memory (max/min)     =          1.0899
     number of positive pivots               =             416
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001112
     time (cpu & wall) for ordering          =        0.000000        0.005790
     time (cpu & wall) for other matrix prep =        0.015625        0.009895
     time (cpu & wall) for value input       =        0.000000        0.000259
     time (cpu & wall) for matrix distrib.   =        0.015625        0.020065
     time (cpu & wall) for numeric factor    =        0.015625        0.046399
     computational rate (gflops) for factor  =        0.024997        0.008418

     no input or output performed

  Solver Memory allocated on core    0       =        0.341 MB
  Solver Memory allocated on core    1       =        0.335 MB
  Solver Memory allocated on core    2       =        0.338 MB
  Solver Memory allocated on core    3       =        0.313 MB
  Total Solver Memory allocated by all cores =        1.326 MB

